name: Feature Request
description: Suggest a new feature or improvement for Contour
type: Feature

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        Please [search existing issues](https://github.com/contour-terminal/contour/issues) to make sure this hasn't been requested already.

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: |
        What problem does this feature solve? Describe the use case or pain point.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: |
        How should this feature work? Describe the desired behavior as concretely as possible.
      placeholder: "It would be great if Contour could..."
    validations:
      required: true

  - type: textarea
    id: alternatives_considered
    attributes:
      label: Alternatives Considered
      description: |
        Have you considered any alternative solutions or workarounds?
      placeholder: "I tried using ... but it doesn't work because..."
    validations:
      required: false

  - type: input
    id: spec_reference
    attributes:
      label: VT Sequence / Specification Reference
      description: |
        If applicable, link to a relevant terminal specification (xterm, VT520, kitty, iTerm2, etc.).
      placeholder: "https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#..."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, mockups, or references for this feature request.
        You can paste screenshots directly into this field.
    validations:
      required: false
