# Emits the shell-integration scripts as C++ data, for `contour generate integration` to print.
#
# Run as:
#   cmake -D SHELLS="bash;fish;…" -D SOURCE_DIR=<src/contour/cli> -D OUTPUT=<file> -P EmbedShellIntegration.cmake
#
# The scripts are embedded rather than read back from the installed share/ directory so that
# `contour generate integration` works from a build tree, and as plain C++ data rather than a Qt
# resource so that it works in a build configured without Qt at all -- which is the whole point of
# CONTOUR_FRONTEND_GUI=OFF.
#
# A CMake script rather than a compiled generator: nothing has to be built for the host before the
# build proper can start (which cross-compilation would otherwise have to special-case), and CMake
# is by definition present in every build -- the same argument test/e2e/CliVerbs.cmake makes for
# being a CMake script rather than a shell one.
#
# The scripts themselves stay ordinary files under shell-integration/: they are what users source,
# they are installed to share/contour/shell-integration/, and a shell script is far easier to
# review and edit as a script than as anything else. Only the in-binary copy is generated.

foreach(required IN ITEMS SHELLS SOURCE_DIR OUTPUT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "EmbedShellIntegration.cmake: -D ${required}=... is required")
    endif()
endforeach()

set(content "// Generated by EmbedShellIntegration.cmake -- do not edit.
//
// Source of truth: src/contour/cli/shell-integration/shell-integration.<shell>
#pragma once

#include <contour/cli/ShellIntegration.hpp>

#include <array>
#include <string_view>

namespace contour::cli::detail
{

")

set(rows "")

foreach(shell IN LISTS SHELLS)
    set(scriptFile "${SOURCE_DIR}/shell-integration/shell-integration.${shell}")
    if(NOT EXISTS "${scriptFile}")
        message(FATAL_ERROR "EmbedShellIntegration.cmake: no script for shell '${shell}' at ${scriptFile}")
    endif()

    # Every byte as its own escape, rather than a string literal: the scripts contain quotes,
    # backslashes and dollar signs by the hundred, and a byte-wise array needs no escaping rules of
    # its own to get them through intact. It also keeps the data out of the string-literal length
    # limits that some compilers impose.
    file(READ "${scriptFile}" hexBytes HEX)
    string(REGEX MATCHALL "[0-9a-f][0-9a-f]" byteList "${hexBytes}")

    # Line endings normalized to LF, because a shell script with CRLF in it is a broken shell script
    # -- the CR ends up part of every command -- and a checkout on Windows hands these over with
    # CRLF. It also makes the embedded bytes the same on every platform regardless of the
    # developer's git settings. Config.cpp's readFile() normalizes the same way for the same reason.
    #
    # Done on the byte LIST rather than the hex string so the match stays aligned to byte
    # boundaries: "0d0a" also occurs in the middle of the byte sequence a0 d0 a5, which a plain
    # string replace would happily corrupt. The list's own ';' separators rule that out.
    string(REPLACE "0d;0a" "0a" byteList "${byteList}")

    list(TRANSFORM byteList PREPEND "'\\x")
    list(TRANSFORM byteList APPEND "'")

    # Wrapped at 16 bytes per line, because a single line of 15k elements is a line-length limit
    # waiting to be found. list(SUBLIST) clamps a length that runs past the end, so the final short
    # chunk needs no special case.
    list(LENGTH byteList byteCount)
    set(bytes "")
    set(index 0)
    while(index LESS byteCount)
        list(SUBLIST byteList ${index} 16 chunk)
        list(JOIN chunk ", " chunkText)
        string(APPEND bytes "    ${chunkText},\n")
        math(EXPR index "${index} + 16")
    endwhile()

    # CamelCase, because generated code is still linted: readability-identifier-naming wants
    # ConstexprVariableCase CamelCase, and a `ShellIntegration_bash` reaches clang-tidy through the
    # translation unit that includes this header just as a hand-written name would.
    string(SUBSTRING "${shell}" 0 1 shellInitial)
    string(TOUPPER "${shellInitial}" shellInitial)
    string(SUBSTRING "${shell}" 1 -1 shellRest)
    set(symbol "ShellIntegration${shellInitial}${shellRest}")

    # std::to_array rather than std::array's CTAD, which cannot take this many elements: libstdc++'s
    # deduction guide checks the element types with a fold expression over all of them, and clang
    # rejects a fold of more than 2048 arguments outright ("exceeded expression nesting limit").
    # to_array deduces the length from the array bound instead, so nothing here writes a size down
    # twice, and it compiles the largest of these scripts in a fraction of a second.
    string(APPEND content "constexpr auto ${symbol} = std::to_array<char>({\n${bytes}});\n\n")
    string(APPEND rows
           "    ShellIntegrationRow { \"${shell}\", std::string_view { ${symbol}.data(), ${symbol}.size() } },\n")
endforeach()

string(APPEND content "/// Every shell this binary carries an integration script for, in the order
/// CONTOUR_SHELL_INTEGRATION_SHELLS lists them.
constexpr auto ShellIntegrationTable = std::array {
${rows}};

} // namespace contour::cli::detail
")

file(WRITE "${OUTPUT}" "${content}")
