if(APPLE)
    include(FindBoost)
    find_package(Boost 1.6 REQUIRED COMPONENTS filesystem)
    include_directories(${Boost_INCLUDE_DIRS})
    set(USING_BOOST TRUE)
    set(FILESYSTEM_FOUND TRUE)
endif()
