if(${USE_BOOST_FILESYSTEM} OR APPLE)
    include(FindBoost)
    find_package(Boost 1.6 REQUIRED COMPONENTS filesystem)
    include_directories(${Boost_INCLUDE_DIRS})
    set(USING_BOOST_FILESYSTEM TRUE PARENT_SCOPE)
    set(USING_BOOST_FILESYSTEM TRUE)
    message(STATUS "[FilesystemResolver]: Using boost::filesystem API")
else()
    set(USING_BOOST_FILESYSTEM FALSE PARENT_SCOPE)
    set(USING_BOOST_FILESYSTEM FALSE)
    message(STATUS "[FilesystemResolver]: Using standard C++ filesystem API")
endif()

